### ISSUE TITLE
Change Duration unit return type to integer

### ISSUE THREAD

**Issue by jonrandahl** [epimorphics/data_services_api#9]
Based on current conversations with @andrew-pickin-epi, et al, the `duration` value returned from the gem's error control needs to be the expected `integer` type to resolve issues with the current tooling.

Also noted in these tickets:

- https://github.com/epimorphics/hmlr-linked-data/issues/111
- https://github.com/epimorphics/hmlr-linked-data/issues/104

## Definition of done:
- [x] Resolve the elapsed value to be in microseconds and presented as an integer

**Comment by tomguilbert** [comment]
@jonrandahl during some ticket gardening we spotted that this looks like a duplicate of https://github.com/epimorphics/json-rails-logger/issues/41 - is that true and do you need both?

**Comment by jonrandahl** [comment]
Finally finished!
